import numpy as np
from common import B,DESIGN_NAMES,X_and_probes,write_result

X,probes=X_and_probes()
name_to_i={r['name']:i for i,r in enumerate(probes)}
design_idx=[name_to_i[n] for n in DESIGN_NAMES]
hold_idx=[i for i in range(len(probes)) if i not in design_idx]
D=X[design_idx]@B
H=X[hold_idx]@B

z_true=np.asarray([0.30,-0.20])
y_design=D@z_true
z_hat=np.linalg.solve(D,y_design)
y_hold_true=H@z_true
y_hold_pred=H@z_hat
in_err=float(np.max(np.abs(y_hold_true-y_hold_pred)))

# Frozen out-of-family truth, not generated by B.
theta_out=np.asarray([0.20,-0.15,0.10,-0.08,0.05,0.02])
yd_out=X[design_idx]@theta_out
z_out=np.linalg.solve(D,yd_out)
yh_out=X[hold_idx]@theta_out
yh_fit=H@z_out
res=float(np.linalg.norm(yh_out-yh_fit)/max(np.linalg.norm(yh_out),1e-15))

out={
 'test':'two-latent structured generator: calibration versus prospective holdouts',
 'design_names':DESIGN_NAMES,
 'holdout_names':[probes[i]['name'] for i in hold_idx],
 'design_matrix':D,
 'design_rank':int(np.linalg.matrix_rank(D,tol=1e-12)),
 'in_family_z_true':z_true,
 'in_family_z_recovered':z_hat,
 'in_family_max_holdout_error':in_err,
 'out_of_family_theta':theta_out,
 'out_of_family_fitted_z':z_out,
 'out_of_family_normalized_holdout_residual':res,
 'design_rank_2':int(np.linalg.matrix_rank(D,tol=1e-12))==2,
 'two_latent_generator_is_predictive_inside_class':in_err<=1e-12,
 'two_latent_generator_is_falsifiable_outside_class':res>=0.05,
 'independent_physics_credit':False,
 'comparator_novelty_credit':False,
 'conclusion':'A compact two-latent generator can be strongly predictive and falsifiable inside a restricted class, but predictive compression alone does not supply independent physical provenance or novelty.'
}
write_result('two_latent_generator',out)
