import json, pathlib, sys
required=['wave22_rank','codimension_bounds','probe_composition','generalized_eh_scenarios','rank_cap_robustness','information_firewall']
files={n:pathlib.Path(f'wave30_downloads/wave30-{n}/wave30_{n}.json') for n in required}
missing=[n for n,p in files.items() if not p.exists()]
if missing:
    print(json.dumps({'missing':missing},indent=2)); sys.exit(2)
data={n:json.loads(p.read_text()) for n,p in files.items()}
signals={}
for d in data.values(): signals.update(d.get('signals',{}))
expected=['wave22_probe_matrix_rank_is_6','constants_only_residual_codimension_ge_4','first_slope_baseline_quotiented_residual_codimension_ge_2','one_extra_EH_coefficient_residual_codimension_ge_1','one_extra_EH_coefficient_cannot_close_six_dimensions','at_least_two_additional_independent_residual_directions_required_beyond_four_parameter_quadratic_truncation','probe_composition_cannot_raise_latent_rank','generic_transversality_can_saturate_rank_cap_but_not_exceed_it','six_dimensional_closure_requires_explicit_extra_directions_and_transversality','information_firewall_pass']
all_true=all(signals.get(k) is True for k in expected)
summary={'campaign':'residual-nullity-wave30','all_required_present':not missing,'all_predeclared_signals_true':all_true,'signals':{k:signals.get(k,False) for k in expected},'wave22_rank':data['wave22_rank']['rank'],'wave22_condition_number':data['wave22_rank']['condition_number'],'finite_truncation_codimension_bounds':{'k2':4,'k4':2,'k5':1},'blocking_object':'BLOCKED_FINITE_LOW_ENERGY_F2_MANIFOLD_CODIMENSION_AT_LEAST_2_AFTER_BASELINE_QUOTIENT;_ONE_EXTRA_EH_DIRECTION_STILL_LEAVES_CODIMENSION_AT_LEAST_1;_WAVE28_UV_DERIVATIVE_ENSEMBLE_UNCHANGED','scientific_verdict':'Within the declared finite low-energy matching problem, Wave 30 proves a dimension bound. The F2 quadratic sector with constants plus first slopes spans at most four latent directions, so its image in the six-dimensional frozen RQIR proxy target has codimension at least two after generalized-EH/baseline quotienting. Even granting one additional independent generalized-EH residual coefficient raises the cap only to five and leaves codimension at least one. Rank-six closure becomes mathematically possible only after at least two additional independent residual directions are supplied and are transverse; Wave 30 does not grant that physical premise. Probe multiplication and generic transversality can saturate but never exceed the latent rank cap.','next_target':'Freeze Wave-30 certificate if clean. Then Wave 31 should test whether any same-lineage published F2/generalized-EH low-energy structures can supply two independently justified residual directions beyond the four-coefficient quadratic truncation without importing p6/R3 or cross-lineage information. If not, park central-projection closure and return to the Wave-28 missing UV displaced-trajectory object.'}
pathlib.Path('wave30_summary.json').write_text(json.dumps(summary,indent=2,sort_keys=True)); print(json.dumps(summary,indent=2,sort_keys=True))
if not all_true: sys.exit(3)
