#!/usr/bin/env python3
import json
from pathlib import Path

OUT = Path("compute_results")
OUT.mkdir(exist_ok=True)

# Algebraic proxy: for identical 2->2 scalar kinematics with s+t+u=0,
# crossing-symmetric polynomials are generated by sigma2=s^2+t^2+u^2 (degree 2)
# and sigma3=s*t*u (degree 3). This is not a spin-2 amplitude calculation.
# We count allowed monomials sigma2^a sigma3^b up to total degree D.
# Fixing the leading sigma2 coefficient removes one freedom. In the forward
# limit t=0,u=-s, sigma3=0, so every b>=1 direction is invisible to forward-limit
# constraints. This quantifies a generic crossing/forward-positivity blind sector.

records = []
for D in range(2, 19):
    mons = []
    for a in range(0, D // 2 + 1):
        for b in range(0, D // 3 + 1):
            deg = 2*a + 3*b
            if deg == 0 or deg > D:
                continue
            mons.append((a, b, deg))
    # leading low-energy term sigma2 is fixed if present
    unfixed = [m for m in mons if not (m[0] == 1 and m[1] == 0)]
    forward_invisible = [m for m in unfixed if m[1] >= 1]
    forward_visible = [m for m in unfixed if m[1] == 0]
    records.append({
        "max_degree": D,
        "basis_size_nonconstant": len(mons),
        "free_after_fixing_sigma2": len(unfixed),
        "forward_visible_free": len(forward_visible),
        "forward_invisible_free": len(forward_invisible),
        "monomials": [{"a": a, "b": b, "degree": deg} for a,b,deg in mons],
    })

summary = {
    "test": "crossing-symmetric polynomial EFT basis growth with s+t+u=0",
    "scope": "scalarized algebraic proxy; not a graviton-amplitude theorem",
    "generator_degrees": {"sigma2": 2, "sigma3": 3},
    "leading_fixed": "coefficient of sigma2",
    "forward_limit": "sigma3=0, so b>=1 directions are invisible",
    "records": records,
}

(OUT / "crossing_eft_basis.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
lines = [
    "# Crossing-symmetric EFT basis growth",
    "",
    "Scalarized control problem with `s+t+u=0`, generators `sigma2` and `sigma3`, and the leading `sigma2` coefficient fixed.",
    "",
    "| D | basis | free after leading fix | forward-visible free | forward-invisible free |",
    "|---:|---:|---:|---:|---:|",
]
for r in records:
    lines.append(f"| {r['max_degree']} | {r['basis_size_nonconstant']} | {r['free_after_fixing_sigma2']} | {r['forward_visible_free']} | {r['forward_invisible_free']} |")
lines += [
    "",
    "Growth of the `b>=1` sector is an explicit algebraic reminder that crossing plus a fixed leading term and forward-limit information do not generically close higher EFT orders.",
]
(OUT / "crossing_eft_basis.md").write_text("\n".join(lines), encoding="utf-8")
print(json.dumps(summary, indent=2))
