#!/usr/bin/env python3
"""Iter018B / G36-C: prospective optimizer calibration for the validated
shared-classical-noise comparator ingredient.

This gate is deliberately in-family. Hidden targets are generated from the same
shared Gaussian Hamiltonian-noise family validated in G36-P. Hidden source
coordinates are never supplied as optimizer starts. Two independent global
designs (Sobol and Latin hypercube) feed bounded least-squares refinement.

Frozen before result inspection:
  final trace-distance recovery < 2e-3;
  structural finiteness required;
  no threshold changes after seeing outcomes.

Passing this gate only validates the optimizer for this finite shared-noise
family. It does not test RCG-002 and does not authorize a general classical or
semiclassical no-go claim.
"""
import argparse, json, math, sys
from pathlib import Path
import numpy as np
from scipy.optimize import least_squares
from scipy.stats import qmc

sys.path.insert(0, str(Path(__file__).resolve().parent))
from iter011_robustness_suite import I2,I4,RHO0,axis,op,td,exp_super
from iter018a_correlated_classical_noise_validation import d_super,evolve_super

RECOVERY_TOL=2e-3
METHODS=('sobol_lsq','lhs_lsq')
LO=np.array([-math.pi,0.10,-math.pi,0.10,-2.0,-2.0,-4.0],float)
HI=np.array([ math.pi,math.pi-0.10, math.pi,math.pi-0.10, 2.0, 2.0, 1.0],float)


def decode_unit(u):
    return LO+(HI-LO)*np.asarray(u,float)


def shared_state(x):
    aaz,apol,baz,bpol,cA,cB,logk=np.asarray(x,float)
    A=op(axis(aaz,apol)); B=op(axis(baz,bpol)); kappa=float(np.exp(logk))
    F=cA*np.kron(A,I2)+cB*np.kron(I2,B)
    E=exp_super(kappa*d_super(F))
    return evolve_super(E)


def residual_u(u,tar):
    r=shared_state(decode_unit(u))-tar
    return np.concatenate((r.real.ravel(),r.imag.ravel()))


def design(method,n,seed):
    if method=='sobol_lsq':
        m=int(math.ceil(math.log2(n)))
        return qmc.Sobol(d=7,scramble=True,seed=seed).random_base2(m)[:n]
    if method=='lhs_lsq':
        return qmc.LatinHypercube(d=7,seed=seed).random(n)
    raise ValueError(method)


def hidden_target(shard):
    rng=np.random.default_rng(36100+shard)
    # Deliberately interior coordinates; not reused as optimizer starts.
    u=np.array([
      rng.uniform(0.08,0.92),rng.uniform(0.08,0.92),
      rng.uniform(0.08,0.92),rng.uniform(0.08,0.92),
      rng.uniform(0.12,0.88),rng.uniform(0.12,0.88),rng.uniform(0.12,0.88)
    ])
    x=decode_unit(u)
    return x,shared_state(x)


def optimize(method,shard,tar):
    pts=design(method,64,36200+100*shard+(0 if method=='sobol_lsq' else 1))
    scored=[]
    for u in pts:
        rr=residual_u(u,tar)
        scored.append((float(np.dot(rr,rr)),u))
    scored.sort(key=lambda z:z[0])
    best=None
    for _,u0 in scored[:12]:
        fit=least_squares(lambda u:residual_u(u,tar),u0,bounds=(0.0,1.0),max_nfev=500,xtol=1e-11,ftol=1e-11,gtol=1e-11)
        rho=shared_state(decode_unit(fit.x)); gap=float(td(rho,tar))
        cand=(gap,fit)
        if best is None or gap<best[0]: best=cand
    gap,fit=best
    return gap,decode_unit(fit.x),int(fit.nfev),float(np.linalg.norm(fit.fun))


def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--method',choices=METHODS,required=True); ap.add_argument('--shard',type=int,choices=range(6),required=True); ap.add_argument('--out',required=True)
    a=ap.parse_args()
    hidden,tar=hidden_target(a.shard)
    gap,xhat,nfev,resnorm=optimize(a.method,a.shard,tar)
    valid=bool(np.isfinite(gap) and np.all(np.isfinite(xhat)) and np.isfinite(resnorm))
    support=bool(valid and gap<RECOVERY_TOL)
    out={
      'iteration':'Iter018B','gate':'G36-C','method':a.method,'shard':a.shard,
      'result':{'best_trace_gap':gap,'scientific_support':support,'nfev':nfev,'residual_norm':resnorm},
      'hidden_target_metadata':{'family':'shared Gaussian classical Hamiltonian noise','hidden_coordinates_not_used_as_starts':True},
      'structural_valid':valid,'frozen_thresholds':{'in_family_recovery_trace_distance':RECOVERY_TOL},
      'interpretation':'Prospective in-family optimizer calibration only. Passing authorizes an RCG-002 adversarial test in this finite shared-noise family; it is not itself an adversarial result.',
      'scope_lock':'Shared Gaussian Hamiltonian noise generated by one collective classical scalar process coupled to two local Pauli axes; no arbitrary nonlocal Lindblad operators.'
    }
    Path(a.out).parent.mkdir(parents=True,exist_ok=True); Path(a.out).write_text(json.dumps(out,indent=2)); print(json.dumps(out,indent=2))
    if not valid: raise SystemExit(2)

if __name__=='__main__': main()
