#!/usr/bin/env python3
"""Iter008 / G26: measurement-feedback master-equation comparator.

Scope lock: this tests an explicit two-qubit continuous Markovian comparator family,
not all semiclassical/classical-channel gravity models.

Comparator:
  d rho/dt = -i chi [ZA ZB, rho] + GA D[ZA]rho + GB D[ZB]rho
with GA*GB = chi^2 and asymmetry a optimized through
  GA = |chi| exp(a), GB = |chi| exp(-a).
The product constraint is the preregistered measurement-feedback trade-off used by
this surrogate family.  We compare the best member against the noiseless coherent
RCG target generated by the same ZZ phase.
"""
import argparse, json, math
from pathlib import Path
import numpy as np

I2=np.eye(2,dtype=complex)
X=np.array([[0,1],[1,0]],dtype=complex)
Z=np.array([[1,0],[0,-1]],dtype=complex)
ZA=np.kron(Z,I2); ZB=np.kron(I2,Z); ZZ=ZA@ZB
PLUS=np.array([1,1],dtype=complex)/math.sqrt(2)
PSI0=np.kron(PLUS,PLUS)
RHO0=np.outer(PSI0,PSI0.conj())


def negativity(rho):
    r=rho.reshape(2,2,2,2).transpose(0,3,2,1).reshape(4,4)
    ev=np.linalg.eigvalsh((r+r.conj().T)/2)
    return float(np.sum(np.abs(ev[ev<0])))


def trace_distance(a,b):
    s=np.linalg.svd(a-b,compute_uv=False)
    return float(0.5*np.sum(s))


def unitary_target(theta):
    # exp(-i theta ZZ), using ZZ^2=I
    U=math.cos(theta)*np.eye(4)-1j*math.sin(theta)*ZZ
    return U@RHO0@U.conj().T


def liouvillian(chi,ga,gb):
    I4=np.eye(4,dtype=complex)
    H=chi*ZZ
    # vec convention: vec(A rho B) = (B^T kron A) vec(rho)
    L=-1j*(np.kron(I4,H)-np.kron(H.T,I4))
    for rate,A in [(ga,ZA),(gb,ZB)]:
        A2=A.conj().T@A
        L += rate*(np.kron(A.conj(),A)-0.5*np.kron(I4,A2)-0.5*np.kron(A2.T,I4))
    return L


def evolve(L,t=1.0):
    w,v=np.linalg.eig(L)
    vinv=np.linalg.inv(v)
    E=v@np.diag(np.exp(w*t))@vinv
    out=(E@RHO0.reshape(-1,order='F')).reshape(4,4,order='F')
    out=(out+out.conj().T)/2
    out/=np.trace(out)
    return out


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--scale',type=float,required=True)
    ap.add_argument('--theta',type=float,required=True)
    ap.add_argument('--tag',required=True)
    ap.add_argument('--out',required=True)
    args=ap.parse_args()

    theta=args.scale*args.theta
    chi=theta # t=1
    target=unitary_target(theta)
    target_neg=negativity(target)
    grid=np.linspace(-3.0,3.0,1201)
    best=None
    min_neg=1e9; max_neg=-1
    for a in grid:
        ga=abs(chi)*math.exp(float(a)); gb=abs(chi)*math.exp(float(-a))
        rho=evolve(liouvillian(chi,ga,gb))
        td=trace_distance(rho,target)
        neg=negativity(rho)
        eigmin=float(np.min(np.linalg.eigvalsh(rho)))
        rec={'a':float(a),'ga':ga,'gb':gb,'td':td,'neg':neg,'eigmin':eigmin}
        if best is None or td<best['td']: best=rec
        min_neg=min(min_neg,neg); max_neg=max(max_neg,neg)

    # Balanced point is theoretically minimum GA+GB under fixed product.
    balanced=evolve(liouvillian(chi,abs(chi),abs(chi)))
    bal_td=trace_distance(balanced,target)
    bal_neg=negativity(balanced)

    # Hard gates are intentionally structural/numerical, not a claim that all
    # classical gravity is excluded.
    gates={
      'target_entangles': target_neg>1e-6,
      'best_state_physical': best['eigmin']>-1e-9,
      'tradeoff_product_exact': abs(best['ga']*best['gb']-chi*chi)<1e-10+1e-8*chi*chi,
      'nonzero_best_gap': best['td']>1e-4,
      'balanced_near_optimal': bal_td <= best['td']+2e-4,
      'comparator_no_more_entangled_than_target': max_neg <= target_neg+1e-8,
    }
    result={
      'iteration':'Iter008','gate':'G26','tag':args.tag,'scale':args.scale,
      'theta_base':args.theta,'theta':theta,'chi':chi,'target_negativity':target_neg,
      'best':best,'balanced':{'td':bal_td,'neg':bal_neg},
      'min_comparator_negativity':min_neg,'max_comparator_negativity':max_neg,
      'gates':gates,'pass':bool(all(gates.values())),
      'scope_lock':'Explicit Markovian ZZ + local-dephasing measurement-feedback surrogate with GA*GB=chi^2 only; not a no-go theorem for all semiclassical gravity.'
    }
    Path(args.out).parent.mkdir(parents=True,exist_ok=True)
    Path(args.out).write_text(json.dumps(result,indent=2),encoding='utf-8')
    print(json.dumps(result,indent=2))
    if not result['pass']: raise SystemExit(2)

if __name__=='__main__': main()
