#!/usr/bin/env python3
"""Iter018A / G36-P: preregistered implementation validation for a broader
classical comparator ingredient: shared Gaussian classical Hamiltonian noise.

This is independent of the still-running G35 verdict and cannot promote RCG-002.
The channel is generated by

  L_cc rho = kappa D[F] rho = -(kappa/2) [F,[F,rho]],
  F = c_A A\otimes I + c_B I\otimes B,

with Hermitian local Pauli-axis observables A,B. Because the two local terms
commute, exp(-i phi F) factorizes into a product unitary for every classical
Gaussian realization phi. Therefore exp(t L_cc) is a convex mixture of product
unitaries, a deliberately classical/shared-noise extension rather than an
arbitrary nonlocal Lindblad channel.

Frozen checks before result inspection:
  TP generator residual < 1e-10
  Choi min eigenvalue > -1e-8
  state min eigenvalue > -1e-8 and trace error < 1e-10
  matrix-exponential vs 80-point Gaussian random-unitary quadrature TD < 1e-10
  product-unitary factorization error < 1e-12
  output negativity from the fixed product input < 1e-10
Scientific failure is recorded in JSON; only nonfinite/invalid numerics fail CI.
"""
import argparse, json, math, sys
from pathlib import Path
import numpy as np
from numpy.polynomial.hermite import hermgauss

sys.path.insert(0, str(Path(__file__).resolve().parent))
from iter011_robustness_suite import I2,I4,RHO0,axis,op,td,neg,exp_super,choi

TH={
 'tp':1e-10,'choi_floor':-1e-8,'state_floor':-1e-8,'trace':1e-10,
 'quadrature_td':1e-10,'factorization':1e-12,'negativity':1e-10,
}

def d_super(Q):
    Q2=Q.conj().T@Q
    return np.kron(Q.conj(),Q)-0.5*np.kron(I4,Q2)-0.5*np.kron(Q2.T,I4)

def evolve_super(E,rho=RHO0):
    r=(E@rho.reshape(-1,order='F')).reshape(4,4,order='F')
    r=(r+r.conj().T)/2
    return r/np.trace(r)

def local_pauli_u(Q,x):
    return math.cos(x)*I2-1j*math.sin(x)*Q

def gaussian_mixture(A,B,cA,cB,kappa,n=80):
    # phi ~ N(0,kappa), t=1; Hermite quadrature expectation.
    xs,ws=hermgauss(n); out=np.zeros((4,4),dtype=complex)
    sigma=math.sqrt(kappa)
    max_factor_err=0.0
    for x,w in zip(xs,ws):
        phi=math.sqrt(2.0)*sigma*float(x)
        UA=local_pauli_u(A,phi*cA); UB=local_pauli_u(B,phi*cB)
        Up=np.kron(UA,UB)
        F=cA*np.kron(A,I2)+cB*np.kron(I2,B)
        ew,V=np.linalg.eigh(F)
        Uf=(V*np.exp(-1j*phi*ew))@V.conj().T
        max_factor_err=max(max_factor_err,float(np.linalg.norm(Uf-Up)))
        out += (float(w)/math.sqrt(math.pi))*(Up@RHO0@Up.conj().T)
    out=(out+out.conj().T)/2; out/=np.trace(out)
    return out,max_factor_err

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--shard',type=int,choices=range(12),required=True); ap.add_argument('--out',required=True)
    a=ap.parse_args(); s=a.shard
    rng=np.random.default_rng(36000+s)
    A=op(axis(rng.uniform(-math.pi,math.pi),rng.uniform(0.15,math.pi-0.15)))
    B=op(axis(rng.uniform(-math.pi,math.pi),rng.uniform(0.15,math.pi-0.15)))
    cA=float(rng.uniform(-1.8,1.8)); cB=float(rng.uniform(-1.8,1.8)); kappa=float(10**rng.uniform(-2.0,0.35))
    F=cA*np.kron(A,I2)+cB*np.kron(I2,B)
    L=kappa*d_super(F); E=exp_super(L); rho=evolve_super(E)
    trrow=I4.reshape(-1,order='F').conj()
    tp=float(np.linalg.norm(trrow@L)); ce=float(np.min(np.linalg.eigvalsh(choi(E))))
    state_min=float(np.min(np.linalg.eigvalsh(rho))); trace_err=float(abs(np.trace(rho)-1.0))
    mix,factor_err=gaussian_mixture(A,B,cA,cB,kappa,80)
    quad_gap=float(td(rho,mix)); negativity=float(neg(rho))
    support=bool(tp<TH['tp'] and ce>TH['choi_floor'] and state_min>TH['state_floor'] and trace_err<TH['trace'] and quad_gap<TH['quadrature_td'] and factor_err<TH['factorization'] and negativity<TH['negativity'])
    vals=[tp,ce,state_min,trace_err,quad_gap,factor_err,negativity,cA,cB,kappa]
    valid=bool(np.all(np.isfinite(vals)))
    out={
      'iteration':'Iter018A','gate':'G36-P','shard':s,
      'parameters':{'cA':cA,'cB':cB,'kappa':kappa},
      'result':{'tp_generator_residual':tp,'choi_min_eig':ce,'state_min_eig':state_min,'trace_error':trace_err,'random_unitary_quadrature_td':quad_gap,'product_unitary_factorization_error':factor_err,'output_negativity_from_product_input':negativity,'scientific_support':support},
      'structural_valid':valid,'frozen_thresholds':TH,
      'interpretation':'Implementation/provenance validation for a shared-classical-noise comparator ingredient only; no RCG-002 adversarial test and no general semiclassical claim.',
      'scope_lock':'Shared Gaussian classical Hamiltonian noise represented as a convex mixture of product unitaries; not arbitrary nonlocal Lindblad noise.'
    }
    Path(a.out).parent.mkdir(parents=True,exist_ok=True); Path(a.out).write_text(json.dumps(out,indent=2)); print(json.dumps(out,indent=2))
    if not valid: raise SystemExit(2)

if __name__=='__main__': main()
