#!/usr/bin/env python3
import argparse,json,pathlib,subprocess

PASS="PASS_SCOPED_RCG011_NEW_PARENT_PRINCIPLE_FAMILY_SELECTED_PREOUTCOME"
BLOCK_HIDDEN="BLOCKED_SCOPED_RCG011_FORMED_FAMILIES_LEAVE_HIDDEN_MODEL_DATA"
BLOCK_SELECT="BLOCKED_SCOPED_RCG011_NO_PREOUTCOME_PARENT_PRINCIPLE_FAMILY_SELECTED"
INVALID="INVALID_RCG011_IMPLEMENTATION_OR_PROVENANCE"
FIELDS=["E1_EXPLICITLY_NEW_MODEL_CONTENT","E2_EXACT_SOURCE_SPACE","E3_EXACT_DOMAIN","E4_TRANSFORMATION_OR_EQUIVALENCE_LAW","E5_CAUSAL_OR_ORDERING_RULE","E6_NORMALIZATION_OR_PHYSICAL_EQUIVALENCE_CLASS","E7_STATE_MEASURE_OR_PREPARATION_CONSTITUTION","E8_GENERATING_OR_RESPONSE_RULE_WITH_SELECTION_POWER","E9_CANDIDATE_INDEPENDENCE","E10_INDEPENDENT_PREOUTCOME_SELECTION_AUTHORITY","E11_NO_HIDDEN_PLACEHOLDERS","E12_OUTCOME_FIREWALL"]

def hb(p): return subprocess.check_output(["git","hash-object",p],text=True).strip()
def must(p,*xs):
 t=pathlib.Path(p).read_text(encoding="utf-8"); miss=[x for x in xs if x not in t]
 if miss: raise SystemExit(f"missing critic evidence {p}: {miss}")
def eligible(row):
 req=[x for x in FIELDS if x!="E10_INDEPENDENT_PREOUTCOME_SELECTION_AUTHORITY"]
 return all(row[x]=="PASS" or (x=="E5_CAUSAL_OR_ORDERING_RULE" and row[x]=="NOT_APPLICABLE") for x in req)
def classify(rows,prov=True,controls=True):
 if not prov or not controls:return INVALID
 elig=[k for k,v in rows.items() if eligible(v)]
 if not elig:return BLOCK_HIDDEN
 sel=[k for k in elig if rows[k]["E10_INDEPENDENT_PREOUTCOME_SELECTION_AUTHORITY"]=="PASS_LEVEL_III"]
 return PASS if len(sel)==1 else BLOCK_SELECT

def main():
 ap=argparse.ArgumentParser(); ap.add_argument("--manifest",required=True); ap.add_argument("--out",required=True); a=ap.parse_args()
 m=json.load(open(a.manifest,encoding="utf-8"))
 prov=all(hb(r["path"])==r["blob"] for r in m["authority_records"])
 if not prov: raise SystemExit("critic provenance failure")
 must("results/RCG002_RSC_CSA1_CLOSED_SOURCE_ACTION_PROPOSAL_TERMINAL.md",
      "The missing datum is therefore not merely","candidate-owned source constitution")
 must("results/RCG002_RSC_SCPT1_SOURCE_CONSTITUTION_TRIAGE_TERMINAL.md",
      "NO_PREOUTCOME_SOURCE_CONSTITUTION_SELECTED","field redefinitions are not fixed")
 must("results/RCG002_RSC_QCPT1_QUANTUM_CONSTITUTION_TRIAGE_TERMINAL.md",
      "NO_PREOUTCOME_QUANTUM_CONSTITUTION_SELECTED","same microscopic unitary")
 must("results/RCG002_RSC_MAPF1_MINIMAL_MULTI_AXIOM_PACKAGE_FORMATION_TERMINAL.md",
      "RSC_PACKAGE_SCHEMA_ONLY_MODEL_DEFINITION_INCOMPLETE","S3-S7 are unpopulated")
 must("results/RCG002_RSC_AB1_NEW_AXIOM_ANCHOR_BUDGET_TERMINAL.md",
      "No slot reaches anchor budget 3.","STRUCTURAL_ANCHOR != MODEL_DEFINITION_SELECTOR")
 must("results/RCG002_RSC_S2PA1_SPIN2_CONSISTENCY_PREMISE_AUTHORITY_TERMINAL.md",
      "NO_SPIN2_CONSISTENCY_PREMISE_CLASS_FORCED_BY_CURRENT_RQIRCG_SCOPED","relational observable discipline")
 must("docs/RQIRCG_MODEL_DEFINITION_SLOT_GRAPH.md",
      "UNRESOLVED_MODEL_DEFINITION_SLOT","STATE_MEASURE_SELECTION != QUANTUM_LAW_MATCHING_SELECTION")
 must("results/RCG010_PARENT_SOURCE_PRINCIPLE_DERIVABILITY_TERMINAL.md",
      "prospectively new model-defining principle or axiom package","actual selection power")

 # Independent reconstruction of the same logical matrix.
 rows={
 "F1_CLOSED_VARIATIONAL_SOURCE_GENERATOR":{
  "E1_EXPLICITLY_NEW_MODEL_CONTENT":"PASS","E2_EXACT_SOURCE_SPACE":"FAIL_SOURCE_ONTOLOGY_UNFIXED",
  "E3_EXACT_DOMAIN":"FAIL_PHYSICAL_SOURCE_DOMAIN_UNFIXED","E4_TRANSFORMATION_OR_EQUIVALENCE_LAW":"FAIL_FIELD_BASIS_AND_SOURCE_QUOTIENT_UNFIXED",
  "E5_CAUSAL_OR_ORDERING_RULE":"FAIL_NOT_DEFINED_BY_VARIATIONAL_WORDING","E6_NORMALIZATION_OR_PHYSICAL_EQUIVALENCE_CLASS":"FAIL_EQUIVALENCE_CLASS_UNFIXED",
  "E7_STATE_MEASURE_OR_PREPARATION_CONSTITUTION":"FAIL_STATE_MEASURE_MISSING","E8_GENERATING_OR_RESPONSE_RULE_WITH_SELECTION_POWER":"FAIL_ACTION_CONTENT_UNDERDEFINED",
  "E9_CANDIDATE_INDEPENDENCE":"PASS","E10_INDEPENDENT_PREOUTCOME_SELECTION_AUTHORITY":"FAIL_LEVEL_II_ONLY",
  "E11_NO_HIDDEN_PLACEHOLDERS":"FAIL_HIDDEN_MODEL_CONTENT","E12_OUTCOME_FIREWALL":"PASS"},
 "F2_CAUSAL_POSITIVE_INFLUENCE_GENERATOR":{
  "E1_EXPLICITLY_NEW_MODEL_CONTENT":"PASS","E2_EXACT_SOURCE_SPACE":"FAIL_SOURCE_TO_HISTORY_EMBEDDING_UNFIXED",
  "E3_EXACT_DOMAIN":"PASS","E4_TRANSFORMATION_OR_EQUIVALENCE_LAW":"FAIL_HISTORY_EQUIVALENCE_UNFIXED",
  "E5_CAUSAL_OR_ORDERING_RULE":"PASS","E6_NORMALIZATION_OR_PHYSICAL_EQUIVALENCE_CLASS":"PASS",
  "E7_STATE_MEASURE_OR_PREPARATION_CONSTITUTION":"FAIL_STATE_MEASURE_UNSELECTED","E8_GENERATING_OR_RESPONSE_RULE_WITH_SELECTION_POWER":"FAIL_KERNEL_VALUES_NOT_SELECTED",
  "E9_CANDIDATE_INDEPENDENCE":"PASS","E10_INDEPENDENT_PREOUTCOME_SELECTION_AUTHORITY":"FAIL_LEVEL_II_ONLY",
  "E11_NO_HIDDEN_PLACEHOLDERS":"FAIL_HIDDEN_STATE_AND_KERNEL_CONTENT","E12_OUTCOME_FIREWALL":"PASS"},
 "F3_RELATIONAL_COMPOSITION_GENERATOR":{
  "E1_EXPLICITLY_NEW_MODEL_CONTENT":"PASS","E2_EXACT_SOURCE_SPACE":"FAIL_SOURCE_SPACE_UNDEFINED",
  "E3_EXACT_DOMAIN":"FAIL_REPRESENTATION_DOMAIN_UNFIXED","E4_TRANSFORMATION_OR_EQUIVALENCE_LAW":"FAIL_REPRESENTATION_CLASS_UNFIXED",
  "E5_CAUSAL_OR_ORDERING_RULE":"PASS","E6_NORMALIZATION_OR_PHYSICAL_EQUIVALENCE_CLASS":"FAIL_NORMALIZATION_CLASS_UNFIXED",
  "E7_STATE_MEASURE_OR_PREPARATION_CONSTITUTION":"FAIL_STATE_MEASURE_MISSING","E8_GENERATING_OR_RESPONSE_RULE_WITH_SELECTION_POWER":"FAIL_NO_QUANTITATIVE_GENERATOR",
  "E9_CANDIDATE_INDEPENDENCE":"PASS","E10_INDEPENDENT_PREOUTCOME_SELECTION_AUTHORITY":"FAIL_PREMISE_CLASS_NOT_FORCED",
  "E11_NO_HIDDEN_PLACEHOLDERS":"FAIL_HIDDEN_REPRESENTATION_CONTENT","E12_OUTCOME_FIREWALL":"PASS"},
 "F4_JOINT_SOURCE_STATE_GENERATING_PACKAGE":{
  "E1_EXPLICITLY_NEW_MODEL_CONTENT":"PASS","E2_EXACT_SOURCE_SPACE":"FAIL_SCHEMA_PLACEHOLDER",
  "E3_EXACT_DOMAIN":"FAIL_SCHEMA_PLACEHOLDER","E4_TRANSFORMATION_OR_EQUIVALENCE_LAW":"FAIL_SCHEMA_PLACEHOLDER",
  "E5_CAUSAL_OR_ORDERING_RULE":"FAIL_SCHEMA_PLACEHOLDER","E6_NORMALIZATION_OR_PHYSICAL_EQUIVALENCE_CLASS":"FAIL_SCHEMA_PLACEHOLDER",
  "E7_STATE_MEASURE_OR_PREPARATION_CONSTITUTION":"FAIL_SCHEMA_PLACEHOLDER","E8_GENERATING_OR_RESPONSE_RULE_WITH_SELECTION_POWER":"FAIL_SCHEMA_PLACEHOLDER",
  "E9_CANDIDATE_INDEPENDENCE":"PASS","E10_INDEPENDENT_PREOUTCOME_SELECTION_AUTHORITY":"FAIL_NO_LEVEL_III_ANCHOR",
  "E11_NO_HIDDEN_PLACEHOLDERS":"FAIL_PACKAGE_SCHEMA_ONLY","E12_OUTCOME_FIREWALL":"PASS"}
 }
 synthetic={x:"PASS" for x in FIELDS}; synthetic["E10_INDEPENDENT_PREOUTCOME_SELECTION_AUTHORITY"]="PASS_LEVEL_III"
 synth_ok=classify({"S":synthetic},True,True)==PASS
 controls={"SYNTHETIC_FULLY_SPECIFIED_PARENT_PRINCIPLE":"PASS_CLASSIFIER_CONTROL" if synth_ok else "FAIL_CLASSIFIER_CONTROL",
 "ACTION_WORDS_NOT_CONTENT":"REJECT_FALSE_POSITIVE","POSITIVITY_NOT_STATE_SELECTION":"REJECT_FALSE_POSITIVE",
 "RELATIONAL_WORDING_NOT_REPRESENTATION_SELECTOR":"REJECT_FALSE_POSITIVE","PACKAGE_SCHEMA_NOT_CONTENT":"REJECT_FALSE_POSITIVE"}
 elig=[k for k,v in rows.items() if eligible(v)]
 out={"phase":"RCG011_NEW_PARENT_PRINCIPLE_FAMILY_INDEPENDENT_CRITIC","frontier_commit":m["frontier_commit"],
 "family_rows":rows,"structurally_eligible_families":elig,
 "selected_families":[k for k in elig if rows[k]["E10_INDEPENDENT_PREOUTCOME_SELECTION_AUTHORITY"]=="PASS_LEVEL_III"],
 "controls":controls,"controls_ok":synth_ok,"provenance_ok":prov,"classification":classify(rows,prov,synth_ok),
 "new_scientific_fact":"ALL_FROZEN_NEW_PARENT_PRINCIPLE_FAMILIES_RETAIN_HIDDEN_MODEL_CONTENT_BEFORE_SELECTION",
 "residual_blocker":"EXACT_NEW_SOURCE_STATE_GENERATING_CONTENT_MUST_BE_PROSPECTIVELY_SPECIFIED",
 "parent_principle_defined":False,"parent_functional_defined":False,"source_object_defined":False,
 "coefficient_space":"A=span{alpha}","selector_rank":0,"residual_dimension":1,
 "value_derivation_authorized":False,"bridge_authorized":False,"alpha_sensitivity_authorized":False,
 "alpha":"UNSELECTED","chi_ABC":"UNAUTHORIZED_NOT_COMPUTED","THEORY_ESTABLISHED":"0%"}
 pathlib.Path(a.out).parent.mkdir(parents=True,exist_ok=True); pathlib.Path(a.out).write_text(json.dumps(out,indent=2,sort_keys=True)+"\n",encoding="utf-8")
 print(json.dumps(out,sort_keys=True))
if __name__=="__main__": main()
