#!/usr/bin/env python3
import json
import math
import numpy as np
from pathlib import Path
from scipy.optimize import least_squares

# Positive continuum generated by the finite first-order log-density law
# d log rho/dx = (a-1)/x - (b-1)/(1-x), giving a Beta(a,b) density on (0,1).
a_true,b_true=1.7,2.4

def moment(n,a,b):
    # E[x^n] = (a)_n/(a+b)_n
    out=1.0
    for k in range(n):
        out *= (a+k)/(a+b+k)
    return out

m_true=np.array([moment(n,a_true,b_true) for n in range(14)])
design=m_true[1:3]

def residual(logab):
    a,b=np.exp(logab)
    return np.array([moment(1,a,b)-design[0],moment(2,a,b)-design[1]])
fit=least_squares(residual,np.log([1.0,1.0]),xtol=1e-14,ftol=1e-14,gtol=1e-14)
a_fit,b_fit=np.exp(fit.x)
m_pred=np.array([moment(n,a_fit,b_fit) for n in range(14)])

# Variable-coefficient all-order recurrence: m_(n+1)=(a+n)/(a+b+n)m_n.
rec_err=[]
for n in range(13):
    rec_err.append(abs(m_pred[n+1]-((a_fit+n)/(a_fit+b_fit+n))*m_pred[n]))

out={
 "test":"finite differential law generating a positive continuum and all-order moments",
 "generator_equation":"d log rho/dx = (a-1)/x - (b-1)/(1-x)",
 "density_family":"Beta(a,b) continuum on (0,1)",
 "true_parameters":[a_true,b_true],
 "design_moments_m1_m2":design.tolist(),
 "recovered_parameters":[float(a_fit),float(b_fit)],
 "parameter_max_error":float(max(abs(a_fit-a_true),abs(b_fit-b_true))),
 "holdout_m3_to_m13_true":m_true[3:].tolist(),
 "holdout_m3_to_m13_pred":m_pred[3:].tolist(),
 "holdout_max_error":float(np.max(np.abs(m_pred[3:]-m_true[3:]))),
 "moment_recurrence":"m_(n+1)=(a+n)/(a+b+n) m_n",
 "moment_recurrence_max_error":float(max(rec_err)),
 "fixed_Hankel_rank_expected":False,
 "finite_generator_with_continuum_and_infinite_moment_tower":True,
 "conclusion":"A finite two-parameter differential law can generate a genuine positive continuum and an exact all-order variable-coefficient moment recurrence without requiring finite Hankel rank. Two design moments identify the parameters in this family and the remaining moments become prospective holdouts.",
 "scope":"Beta-density architecture proxy; not a proposed graviton spectral law."
}
Path('wave11_results').mkdir(exist_ok=True)
Path('wave11_results/beta_continuum_generator.json').write_text(json.dumps(out,indent=2),encoding='utf-8')
print(json.dumps(out,indent=2))
